spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//192.168.100.121:1521/lcdev
    username: MAHAN
    password: mahan
    hikari:
      schema: MAHAN
  config:
    import:
      - "app-prod.yml"
  profiles:
    active: default
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


cinema:
  salon:
    name: "gol"
    number: 2


